import {
  LayoutDashboard,
  Users,
  Boxes,
  ShoppingCart,
  Settings,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  PlusCircle,
  File,
  ListFilter,
  Search,
  AlarmClock,
  PackageOpen,
  Ticket,
  PieChart,
  SlidersHorizontal,
} from 'lucide-react';

// We only need to export the object containing the components.
export const Icons = {
  dashboard: LayoutDashboard,
  users: Users,
  products: Boxes,
  cart: ShoppingCart,
  settings: Settings,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  ellipsis: MoreHorizontal,
  add: PlusCircle,
  file: File,
  filter: ListFilter,
  search: Search,
  reports: PieChart,
  case: PackageOpen,
  promotions: Ticket,
};